### PR TITLE
(EWL-863): Welcome to storybook v5

### PR DESCRIPTION
**Pull request by JulienKode**
### Migration from storybook v4 to storybook v5

- [x] change to the new parameter api https://storybook.js.org/docs/configurations/options-parameter/
- [x] change the way we use `withKnobs`
- [x] upgrade storybook packages
- [x] interface with Webpack config of storybook v5

Storybook v5

### CODE REVIEW

**Comment by JulienKode** [comment]
@val3ntin thanks for your review, I didn't notice 

I'll take a look at this

**Comment by JulienKode** [comment]
@val3ntin I've added svgs and background

**Comment by val3ntin** [comment]
welldone @JulienKode 

other issues are noticed:
* [AdManager](https://deploy-preview-233--es-web-toolkit.netlify.com/?path=/story/components-advertisement--admanager) - some weird `defaultText` issue.

Screen Shot 2019-07-08 at 10 10 53 AM


it's referenced to addon-info and markdown usage  https://github.com/storybookjs/storybook/issues/6981 and thus just simple deleted the markdown usage from the component as code blocks can't be parsed there yet.
* [livecomments](https://deploy-preview-233--es-web-toolkit.netlify.com/?path=/story/modules-livecomments--comments) inner html seem to be escaped by storybook - need to find a way how to integrate html into the prop.

**Comment by val3ntin** [comment]
@JulienKode have just fixed livecomments char escaping above by providing knobs options.
all is LGTM now ;)

another point is to start checking the built app just to be sure none of dependencies break its usage ;)

**Comment by JulienKode** [comment]
@val3ntin thanks for your update and review

I'll take a look at this

**Comment by JulienKode** [comment]
@val3ntin No components seems broken after the update on `ETS`

Screenshot 2019-07-08 at 10 38 22

**Pull request merged**
